;; ========== BEBIDAS (100) CON INCOMPATIBLES ESPECiFICOS ==========
(deffacts bebidas
   ;; === REFRESCOS (15) ===
   (bebida (nombre "Agua mineral") (no-compatible-con "Callos a la madrileña" "Rabo de toro") (precio 1))
   (bebida (nombre "Coca-Cola") (no-compatible-con "Bacalao al pil-pil" "Merluza a la vasca") (precio 2))
   (bebida (nombre "Fanta Naranja") (no-compatible-con "Riñones al jerez" "Higado encebollado") (precio 2))
   (bebida (nombre "Sprite") (no-compatible-con "Carrillada iberica" "Solomillo al vino") (precio 2))
   (bebida (nombre "Tonica Schweppes") (no-compatible-con "Tarta de chocolate" "Flan de huevo") (precio 2.5))
   (bebida (nombre "Limonada natural") (no-compatible-con "Crema de calabaza" "Sopa de cebolla") (precio 3))
   (bebida (nombre "Zumo de naranja natural") (no-compatible-con "Calamares a la romana" "Pulpo a la gallega") (precio 3.5))
   (bebida (nombre "Zumo de piña") (no-compatible-con "Estofado de ternera" "Lengua estofada") (precio 3))
   (bebida (nombre "Zumo de manzana") (no-compatible-con "Chuleta de cerdo" "Secreto iberico") (precio 3))
   (bebida (nombre "Batido de fresa") (no-compatible-con "Albondigas en salsa" "Morcilla de Burgos") (precio 4))
   (bebida (nombre "Batido de chocolate") (no-compatible-con "Gazpacho" "Salmorejo") (precio 4))
   (bebida (nombre "Batido de vainilla") (no-compatible-con "Chipirones en su tinta" "Gambas al ajillo") (precio 4))
   (bebida (nombre "Granizado de limon") (no-compatible-con "Caldo gallego" "Sopa de pescado") (precio 3.5))
   (bebida (nombre "Granizado de cafe") (no-compatible-con "Tarta de queso" "Natillas caseras") (precio 3.5))
   (bebida (nombre "Agua con gas") (no-compatible-con "Torrijas" "Leche frita") (precio 1.5))

   ;; === CAFeS (10) ===
   (bebida (nombre "Cafe solo") (no-compatible-con "Helado de vainilla" "Tarta de limon") (precio 1.5))
   (bebida (nombre "Cafe con leche") (no-compatible-con "Mejillones al vapor" "Almejas a la marinera") (precio 2))
   (bebida (nombre "Cortado") (no-compatible-con "Trufas de chocolate" "Volcan de chocolate") (precio 1.8))
   (bebida (nombre "Capuccino") (no-compatible-con "Chuleton de buey" "Entrecot a la parrilla") (precio 3))
   (bebida (nombre "Cafe americano") (no-compatible-con "Arroz con leche" "Tocino de cielo") (precio 2))
   (bebida (nombre "Cafe bombon") (no-compatible-con "Ensalada Cesar" "Ensalada griega") (precio 2.5))
   (bebida (nombre "Cafe irlandes") (no-compatible-con "Mousse de frutos rojos" "Tarta de fresa") (precio 5))
   (bebida (nombre "Cafe vienes") (no-compatible-con "Boquerones en vinagre" "Anchoas") (precio 4))
   (bebida (nombre "Descafeinado") (no-compatible-con "Brownie" "Couland de chocolate") (precio 2))
   (bebida (nombre "Carajillo") (no-compatible-con "Flan de huevo" "Natillas caseras") (precio 4))

   ;; === TeS E INFUSIONES (10) ===
   (bebida (nombre "Te negro") (no-compatible-con "Tarta de queso" "Crema de chocolate") (precio 2))
   (bebida (nombre "Te verde") (no-compatible-con "Torrijas" "Buñuelos de viento") (precio 2))
   (bebida (nombre "Te rojo") (no-compatible-con "Costillas BBQ" "Pato a la naranja") (precio 2.5))
   (bebida (nombre "Te chai") (no-compatible-con "Dorada a la sal" "Lubina con patatas") (precio 3))
   (bebida (nombre "Manzanilla") (no-compatible-con "Presa iberica" "Pluma iberica") (precio 2))
   (bebida (nombre "Menta poleo") (no-compatible-con "Tarta de Santiago" "Panellets") (precio 2))
   (bebida (nombre "Tila") (no-compatible-con "Cordero asado" "Cabrito al horno") (precio 2))
   (bebida (nombre "Infusion de frutas del bosque") (no-compatible-con "Chorizo a la sidra" "Salchichas al vino") (precio 2.5))
   (bebida (nombre "Rooibos") (no-compatible-con "Tarta Red Velvet" "Cheesecake") (precio 2.5))
   (bebida (nombre "Infusion digestiva") (no-compatible-con "Callos a la madrileña" "Rabo de toro") (precio 2.5))

   ;; === CERVEZAS (15) ===
   (bebida (nombre "Cerveza rubia") (no-compatible-con "Tarta de chocolate" "Volcan de chocolate") (precio 3))
   (bebida (nombre "Cerveza tostada") (no-compatible-con "Ensalada de quinoa" "Ensalada caprese") (precio 3.5))
   (bebida (nombre "Cerveza negra") (no-compatible-con "Salmon a la plancha" "Atun rojo") (precio 4))
   (bebida (nombre "Cerveza artesanal IPA") (no-compatible-con "Tarta de manzana" "Crumble de manzana") (precio 5))
   (bebida (nombre "Cerveza sin alcohol") (no-compatible-con "Queso a la plancha" "Berenjenas a la parmesana") (precio 2.5))
   (bebida (nombre "Cerveza de trigo") (no-compatible-con "Tarta de frutos rojos" "Mousse de chocolate") (precio 4))
   (bebida (nombre "Cerveza Lager") (no-compatible-con "Tarta de limon" "Tarta de queso") (precio 3))
   (bebida (nombre "Cerveza Stout") (no-compatible-con "Merluza a la vasca" "Bacalao al pil-pil") (precio 4.5))
   (bebida (nombre "Cerveza Pilsner") (no-compatible-con "Estofado de ternera" "Carrillada iberica") (precio 3.5))
   (bebida (nombre "Cerveza Amber") (no-compatible-con "Tarta de fresa" "Macedonia de frutas") (precio 4))
   (bebida (nombre "Cerveza Lambic") (no-compatible-con "Solomillo al vino" "Chuleton de buey") (precio 6))
   (bebida (nombre "Cerveza Bock") (no-compatible-con "Pulpo a la gallega" "Calamares a la romana") (precio 5))
   (bebida (nombre "Cerveza Porter") (no-compatible-con "Tarta de limon" "Tarta de naranja") (precio 4.5))
   (bebida (nombre "Cerveza Sour") (no-compatible-con "Queso de cabra" "Tosta de queso") (precio 5.5))
   (bebida (nombre "Cerveza Barley Wine") (no-compatible-con "Ensalada Waldorf" "Ensalada de espinacas") (precio 7))

   ;; === VINOS (20) ===
   (bebida (nombre "Vino tinto reserva") (no-compatible-con "Bacalao al pil-pil" "Merluza a la vasca") (precio 5))
   (bebida (nombre "Vino tinto joven") (no-compatible-con "Tarta de chocolate" "Flan de huevo") (precio 3.5))
   (bebida (nombre "Vino blanco seco") (no-compatible-con "Chuleton de buey" "Entrecot a la parrilla") (precio 4))
   (bebida (nombre "Vino blanco semidulce") (no-compatible-con "Morcilla de Burgos" "Chorizo a la sidra") (precio 4.5))
   (bebida (nombre "Vino rosado") (no-compatible-con "Torrijas" "Leche frita") (precio 4))
   (bebida (nombre "Cava brut") (no-compatible-con "Carrillada iberica" "Rabo de toro") (precio 6))
   (bebida (nombre "Cava rosado") (no-compatible-con "Tarta de Santiago" "Panellets") (precio 6.5))
   (bebida (nombre "Rioja reserva") (no-compatible-con "Salmon a la plancha" "Atun rojo") (precio 7))
   (bebida (nombre "Ribera del Duero") (no-compatible-con "Pulpo a la gallega" "Mejillones al vapor") (precio 8))
   (bebida (nombre "Vino de Jerez") (no-compatible-con "Tarta de frutos rojos" "Mousse de chocolate") (precio 5))
   (bebida (nombre "Vino de Priorat") (no-compatible-con "Tarta de manzana" "Strudel de manzana") (precio 9))
   (bebida (nombre "Vino Moscatel") (no-compatible-con "Solomillo al vino" "Secreto iberico") (precio 5))
   (bebida (nombre "Vino Oporto") (no-compatible-con "Ensalada Cesar" "Ensalada griega") (precio 6))
   (bebida (nombre "Vino Verdejo") (no-compatible-con "Callos a la madrileña" "Lengua estofada") (precio 5.5))
   (bebida (nombre "Vino Albariño") (no-compatible-con "Cordero asado" "Cabrito al horno") (precio 6))
   (bebida (nombre "Vino Malbec") (no-compatible-con "Tarta de queso" "Natillas caseras") (precio 7))
   (bebida (nombre "Vino Syrah") (no-compatible-con "Tarta Red Velvet" "Cheesecake") (precio 6.5))
   (bebida (nombre "Vino Chardonnay") (no-compatible-con "Chuleton de buey" "Presa iberica") (precio 5.5))
   (bebida (nombre "Vino Sauvignon Blanc") (no-compatible-con "Callos a la madrileña" "Rabo de toro") (precio 5))
   (bebida (nombre "Vino Pinot Noir") (no-compatible-con "Tarta de limon" "Tarta de naranja") (precio 7.5))

   ;; === CoCTELES (20) ===
   (bebida (nombre "Gin Tonic") (no-compatible-con "Tarta de chocolate" "Brownie") (precio 8))
   (bebida (nombre "Mojito") (no-compatible-con "Queso a la plancha" "Berenjenas a la parmesana") (precio 7))
   (bebida (nombre "Margarita") (no-compatible-con "Natillas caseras" "Flan de huevo") (precio 9))
   (bebida (nombre "Piña Colada") (no-compatible-con "Chorizo a la sidra" "Salchichas al vino") (precio 8))
   (bebida (nombre "Caipirinha") (no-compatible-con "Tarta de Santiago" "Panellets") (precio 7.5))
   (bebida (nombre "Bloody Mary") (no-compatible-con "Tarta de frutos rojos" "Mousse de chocolate") (precio 8))
   (bebida (nombre "Cosmopolitan") (no-compatible-con "Callos a la madrileña" "Rabo de toro") (precio 9))
   (bebida (nombre "Daiquiri") (no-compatible-con "Solomillo al vino" "Chuleton de buey") (precio 8))
   (bebida (nombre "Negroni") (no-compatible-con "Tarta de manzana" "Strudel de manzana") (precio 10))
   (bebida (nombre "Old Fashioned") (no-compatible-con "Pulpo a la gallega" "Calamares a la romana") (precio 11))
   (bebida (nombre "Martini") (no-compatible-con "Tarta de chocolate" "Volcan de chocolate") (precio 10))
   (bebida (nombre "Aperol Spritz") (no-compatible-con "Estofado de ternera" "Carrillada iberica") (precio 7))
   (bebida (nombre "Cuba Libre") (no-compatible-con "Tarta de queso" "Natillas caseras") (precio 6))
   (bebida (nombre "Moscow Mule") (no-compatible-con "Tarta Red Velvet" "Cheesecake") (precio 8))
   (bebida (nombre "Whisky Sour") (no-compatible-con "Ensalada Cesar" "Ensalada griega") (precio 9))
   (bebida (nombre "Pisco Sour") (no-compatible-con "Torrijas" "Leche frita") (precio 8.5))
   (bebida (nombre "Sex on the Beach") (no-compatible-con "Morcilla de Burgos" "Chorizo a la sidra") (precio 8))
   (bebida (nombre "Blue Lagoon") (no-compatible-con "Cordero asado" "Cabrito al horno") (precio 7.5))
   (bebida (nombre "Tequila Sunrise") (no-compatible-con "Tarta de limon" "Tarta de naranja") (precio 8))
   (bebida (nombre "Espresso Martini") (no-compatible-con "Bacalao al pil-pil" "Merluza a la vasca") (precio 9))

   ;; === LICORES Y DIGESTIVOS (10) ===
   (bebida (nombre "Brandy") (no-compatible-con "Salmon a la plancha" "Atun rojo") (precio 5))
   (bebida (nombre "Whisky") (no-compatible-con "Tarta de fresa" "Macedonia de frutas") (precio 6))
   (bebida (nombre "Ron") (no-compatible-con "Queso a la plancha" "Berenjenas a la parmesana") (precio 5))
   (bebida (nombre "Vodka") (no-compatible-con "Tarta de chocolate" "Flan de huevo") (precio 5))
   (bebida (nombre "Ginebra") (no-compatible-con "Tarta de queso" "Natillas caseras") (precio 5))
   (bebida (nombre "Tequila") (no-compatible-con "Callos a la madrileña" "Rabo de toro") (precio 6))
   (bebida (nombre "Anis") (no-compatible-con "Pulpo a la gallega" "Calamares a la romana") (precio 4))
   (bebida (nombre "Licor de hierbas") (no-compatible-con "Ensalada Cesar" "Ensalada griega") (precio 5))
   (bebida (nombre "Amaretto") (no-compatible-con "Solomillo al vino" "Chuleton de buey") (precio 5))
   (bebida (nombre "Baileys") (no-compatible-con "Tarta de limon" "Tarta de naranja") (precio 6))
)