;; ========== POSTRES (100) ==========
(deffacts postres
   ;; === CLÁSICOS ESPAÑOLES (20) ===
   (plato (nombre "Flan de huevo") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 4) (ingredientes huevo leche azucar))
   (plato (nombre "Natillas caseras") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 4) (ingredientes leche huevo canela))
   (plato (nombre "Arroz con leche") (tipo postre) (temporada invierno) (estilo regional) (vegetariano si) (precio 5) (ingredientes arroz leche canela))
   (plato (nombre "Torrijas") (tipo postre) (temporada primavera) (estilo regional) (vegetariano si) (precio 6) (ingredientes pan leche miel))
   (plato (nombre "Leche frita") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 5) (ingredientes leche harina canela))
   (plato (nombre "Buñuelos de viento") (tipo postre) (temporada otoño) (estilo regional) (vegetariano si) (precio 5) (ingredientes masa crema azucar))
   (plato (nombre "Polvorones") (tipo postre) (temporada invierno) (estilo regional) (vegetariano si) (precio 3) (ingredientes almendra manteca azucar))
   (plato (nombre "Mantecados") (tipo postre) (temporada invierno) (estilo regional) (vegetariano si) (precio 3) (ingredientes manteca harina canela))
   (plato (nombre "Roscos de vino") (tipo postre) (temporada invierno) (estilo regional) (vegetariano si) (precio 4) (ingredientes vino harina anis))
   (plato (nombre "Panellets") (tipo postre) (temporada otoño) (estilo regional) (vegetariano si) (precio 6) (ingredientes almendra boniato piñones))
   (plato (nombre "Tarta de Santiago") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 7) (ingredientes almendra huevo limon))
   (plato (nombre "Huesos de santo") (tipo postre) (temporada otoño) (estilo regional) (vegetariano si) (precio 5) (ingredientes almendra yema mazapan))
   (plato (nombre "Bartolillos") (tipo postre) (temporada primavera) (estilo regional) (vegetariano si) (precio 5) (ingredientes masa crema limon))
   (plato (nombre "Soplillos") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 4) (ingredientes almendra clara azucar))
   (plato (nombre "Tocino de cielo") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 6) (ingredientes yema azucar agua))
   (plato (nombre "Pestiños") (tipo postre) (temporada primavera) (estilo regional) (vegetariano si) (precio 5) (ingredientes masa miel anis))
   (plato (nombre "Perrunillas") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 3) (ingredientes manteca harina canela))
   (plato (nombre "Magdalenas caseras") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 2) (ingredientes huevo harina limon))
   (plato (nombre "Rosquillas de anís") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 3) (ingredientes harina anis azucar))
   (plato (nombre "Yemas de San Leandro") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 6) (ingredientes yema azucar agua))

   ;; === CHOCOLATE (20) ===
   (plato (nombre "Tarta de chocolate negro") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 7) (ingredientes chocolate nata huevo))
   (plato (nombre "Mousse de chocolate") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 6) (ingredientes chocolate huevo nata))
   (plato (nombre "Brownie") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 5) (ingredientes chocolate nuez harina))
   (plato (nombre "Couland de chocolate") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes chocolate mantequilla huevo))
   (plato (nombre "Trufas de chocolate") (tipo postre) (temporada invierno) (estilo sibarita) (vegetariano si) (precio 9) (ingredientes chocolate nata cacao))
   (plato (nombre "Volcán de chocolate") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes chocolate mantequilla huevo))
   (plato (nombre "Tarta Sacher") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 9) (ingredientes chocolate almendra mermelada))
   (plato (nombre "Profiteroles") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 7) (ingredientes crema chocolate masa))
   (plato (nombre "Palmeras de chocolate") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 4) (ingredientes chocolate hojaldre azucar))
   (plato (nombre "Galletas de chocolate") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 3) (ingredientes chocolate harina mantequilla))
   (plato (nombre "Bizcocho de chocolate") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 5) (ingredientes chocolate huevo harina))
   (plato (nombre "Crema de chocolate") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 6) (ingredientes chocolate leche huevo))
   (plato (nombre "Tarta de chocolate blanco") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes chocolate-blanco frambuesa nata))
   (plato (nombre "Mouse de chocolate blanco") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 6) (ingredientes chocolate-blanco nata huevo))
   (plato (nombre "Tableta de chocolate casera") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 5) (ingredientes chocolate almendra miel))
   (plato (nombre "Bombones variados") (tipo postre) (temporada invierno) (estilo sibarita) (vegetariano si) (precio 10) (ingredientes chocolate nata licor))
   (plato (nombre "Tarta de chocolate y avellana") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes chocolate avellana nata))
   (plato (nombre "Coulant de chocolate y naranja") (tipo postre) (temporada invierno) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes chocolate naranja mantequilla))
   (plato (nombre "Tarta de chocolate y café") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes chocolate cafe nata))
   (plato (nombre "Helado de chocolate") (tipo postre) (temporada verano) (estilo clasico) (vegetariano si) (precio 5) (ingredientes chocolate leche nata))

   ;; === FRUTALES (20) ===
   (plato (nombre "Tarta de manzana") (tipo postre) (temporada otoño) (estilo clasico) (vegetariano si) (precio 6) (ingredientes manzana masa canela))
   (plato (nombre "Macedonia de frutas") (tipo postre) (temporada verano) (estilo clasico) (vegetariano si) (precio 5) (ingredientes melon sandia uva))
   (plato (nombre "Tarta de limón") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 6) (ingredientes limon galleta merengue))
   (plato (nombre "Crumble de manzana") (tipo postre) (temporada invierno) (estilo moderno) (vegetariano si) (precio 6) (ingredientes manzana avena mantequilla))
   (plato (nombre "Tarta de fresa") (tipo postre) (temporada primavera) (estilo moderno) (vegetariano si) (precio 7) (ingredientes fresa nata bizcocho))
   (plato (nombre "Strudel de manzana") (tipo postre) (temporada otoño) (estilo regional) (vegetariano si) (precio 7) (ingredientes manzana pasas hojaldre))
   (plato (nombre "Tarta de pera") (tipo postre) (temporada otoño) (estilo moderno) (vegetariano si) (precio 6) (ingredientes pera almendra masa))
   (plato (nombre "Tarta de kiwi") (tipo postre) (temporada invierno) (estilo moderno) (vegetariano si) (precio 6) (ingredientes kiwi crema bizcocho))
   (plato (nombre "Tarta de melocotón") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 6) (ingredientes melocoton almibar nata))
   (plato (nombre "Tarta de cereza") (tipo postre) (temporada verano) (estilo regional) (vegetariano si) (precio 7) (ingredientes cereza almendra masa))
   (plato (nombre "Tarta de piña") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 6) (ingredientes piña coco bizcocho))
   (plato (nombre "Tarta de mora") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 7) (ingredientes mora nata bizcocho))
   (plato (nombre "Tarta de frambuesa") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes frambuesa chocolate bizcocho))
   (plato (nombre "Tarta de arándanos") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 7) (ingredientes arandano limon bizcocho))
   (plato (nombre "Tarta de mango") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 7) (ingredientes mango coco bizcocho))
   (plato (nombre "Tarta de higo") (tipo postre) (temporada verano) (estilo regional) (vegetariano si) (precio 7) (ingredientes higo nuez masa))
   (plato (nombre "Tarta de ciruela") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 6) (ingredientes ciruela almendra masa))
   (plato (nombre "Tarta de granada") (tipo postre) (temporada otoño) (estilo moderno) (vegetariano si) (precio 7) (ingredientes granada nata bizcocho))
   (plato (nombre "Tarta de coco y lima") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes coco lima bizcocho))
   (plato (nombre "Tarta de frutos rojos") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 9) (ingredientes fresa frambuesa arandano))

   ;; === HELADOS (15) ===
   (plato (nombre "Helado de vainilla") (tipo postre) (temporada verano) (estilo clasico) (vegetariano si) (precio 4) (ingredientes leche vainilla azucar))
   (plato (nombre "Helado de chocolate") (tipo postre) (temporada verano) (estilo clasico) (vegetariano si) (precio 4) (ingredientes leche chocolate azucar))
   (plato (nombre "Helado de fresa") (tipo postre) (temporada verano) (estilo clasico) (vegetariano si) (precio 4) (ingredientes leche fresa azucar))
   (plato (nombre "Helado de limón") (tipo postre) (temporada verano) (estilo clasico) (vegetariano si) (precio 4) (ingredientes leche limon azucar))
   (plato (nombre "Helado de turrón") (tipo postre) (temporada invierno) (estilo regional) (vegetariano si) (precio 5) (ingredientes leche turron azucar))
   (plato (nombre "Helado de mango") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 5) (ingredientes leche mango azucar))
   (plato (nombre "Helado de pistacho") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 6) (ingredientes leche pistacho azucar))
   (plato (nombre "Helado de avellana") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 6) (ingredientes leche avellana azucar))
   (plato (nombre "Helado de café") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 5) (ingredientes leche cafe azucar))
   (plato (nombre "Helado de coco") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 5) (ingredientes leche coco azucar))
   (plato (nombre "Helado de menta") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 5) (ingredientes leche menta chocolate))
   (plato (nombre "Helado de yogur") (tipo postre) (temporada verano) (estilo moderno) (vegetariano si) (precio 4) (ingredientes yogur fruta azucar))
   (plato (nombre "Helado de vainilla con virutas de chocolate") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 6) (ingredientes vainilla chocolate nata))
   (plato (nombre "Helado de queso con frambuesas") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes queso frambuesa nata))
   (plato (nombre "Helado de chocolate blanco con frutos rojos") (tipo postre) (temporada verano) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes chocolate-blanco frutos-rojos nata))

   ;; === INTERNACIONALES (25) ===
   (plato (nombre "Tiramisú") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 7) (ingredientes cafe mascarpone cacao))
   (plato (nombre "Cheesecake") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes queso galleta frambuesa))
   (plato (nombre "Crème brûlée") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes nata huevo azucar))
   (plato (nombre "Profiteroles") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 7) (ingredientes crema chocolate masa))
   (plato (nombre "Cannoli sicilianos") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 6) (ingredientes ricotta pistacho masa))
   (plato (nombre "Baklava") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 6) (ingredientes masa miel nuez))
   (plato (nombre "Panna cotta") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes nata azucar vainilla))
   (plato (nombre "Mochi japonés") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 5) (ingredientes arroz relleno azucar))
   (plato (nombre "Churros con chocolate") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 5) (ingredientes masa azucar chocolate))
   (plato (nombre "Pastel de zanahoria") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 6) (ingredientes zanahoria nuez crema))
   (plato (nombre "Tarta de queso al horno") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes queso huevo nata))
   (plato (nombre "Éclair") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 6) (ingredientes masa crema chocolate))
   (plato (nombre "Macarons") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes almendra merengue relleno))
   (plato (nombre "Tarta de manzana americana") (tipo postre) (temporada todo) (estilo clasico) (vegetariano si) (precio 6) (ingredientes manzana canela masa))
   (plato (nombre "Crepes Suzette") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes masa naranja licor))
   (plato (nombre "Gelato italiano") (tipo postre) (temporada verano) (estilo regional) (vegetariano si) (precio 5) (ingredientes leche fruta azucar))
   (plato (nombre "Tarta de queso japonesa") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes queso huevo nata))
   (plato (nombre "Strudel de manzana austriaco") (tipo postre) (temporada otoño) (estilo regional) (vegetariano si) (precio 7) (ingredientes manzana pasas hojaldre))
   (plato (nombre "Pastel de tres leches") (tipo postre) (temporada todo) (estilo regional) (vegetariano si) (precio 6) (ingredientes leche huevo bizcocho))
   (plato (nombre "Kulfi indio") (tipo postre) (temporada verano) (estilo regional) (vegetariano si) (precio 5) (ingredientes leche azafran pistacho))
   (plato (nombre "Mille-feuille") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes hojaldre crema azucar))
   (plato (nombre "Tarta de queso filadelfia") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes queso galleta frambuesa))
   (plato (nombre "Banoffee") (tipo postre) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes platano toffee nata))
   (plato (nombre "Tarta Red Velvet") (tipo postre) (temporada todo) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes bizcocho crema frambuesa))
   (plato (nombre "Chimney cake") (tipo postre) (temporada invierno) (estilo regional) (vegetariano si) (precio 5) (ingredientes masa azucar canela))
)