;; ==================== PRIMEROS PLATOS (100) ====================
(deffacts primeros-platos
   ;; Sopas y cremas (20)
   (plato (nombre "Gazpacho andaluz") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 4) (ingredientes tomate pepino ajo aceite))
   (plato (nombre "Sopa de cebolla") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano no) (precio 5) (ingredientes cebolla caldo queso pan))
   (plato (nombre "Crema de calabaza") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 6) (ingredientes calabaza zanahoria nata))
   (plato (nombre "Sopa de miso") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 5) (ingredientes miso tofu alga wakame))
   (plato (nombre "Sopa de pescado") (tipo primero) (temporada invierno) (estilo regional) (vegetariano no) (precio 8) (ingredientes pescado tomate ajo))
   (plato (nombre "Crema de champiñones") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano si) (precio 6) (ingredientes champiñones cebolla nata))
   (plato (nombre "Sopa de lentejas") (tipo primero) (temporada invierno) (estilo regional) (vegetariano si) (precio 5) (ingredientes lentejas zanahoria cebolla))
   (plato (nombre "Sopa de tomate") (tipo primero) (temporada todo) (estilo clasico) (vegetariano si) (precio 4) (ingredientes tomate albahaca ajo))
   (plato (nombre "Caldo gallego") (tipo primero) (temporada invierno) (estilo regional) (vegetariano no) (precio 7) (ingredientes grelos patata chorizo))
   (plato (nombre "Sopa de ajo") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano no) (precio 5) (ingredientes ajo pan huevo pimenton))
   (plato (nombre "Vichyssoise") (tipo primero) (temporada verano) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes puerro patata nata))
   (plato (nombre "Sopa de espárragos") (tipo primero) (temporada primavera) (estilo moderno) (vegetariano si) (precio 6) (ingredientes espárragos cebolla leche))
   (plato (nombre "Sopa de marisco") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 9) (ingredientes gambas mejillones caldo))
   (plato (nombre "Crema de zanahoria") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 5) (ingredientes zanahoria jengibre nata))
   (plato (nombre "Sopa minestrone") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano si) (precio 6) (ingredientes verduras pasta tomate))
   (plato (nombre "Sopa de pollo") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano no) (precio 7) (ingredientes pollo zanahoria apio))
   (plato (nombre "Sopa de quinoa") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 6) (ingredientes quinoa espinacas zanahoria))
   (plato (nombre "Sopa de almejas") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 8) (ingredientes almejas ajo perejil))
   (plato (nombre "Crema de brócoli") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 6) (ingredientes brócoli patata queso))
   (plato (nombre "Sopa de verduras") (tipo primero) (temporada todo) (estilo clasico) (vegetariano si) (precio 5) (ingredientes zanahoria calabacin puerro))

   ;; Ensaladas (30)
   (plato (nombre "Ensalada César") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes lechuga pollo croutons parmesano))
   (plato (nombre "Ensalada griega") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 6) (ingredientes tomate pepino queso-feta aceitunas))
   (plato (nombre "Ensalada de quinoa") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 8) (ingredientes quinoa aguacate granada))
   (plato (nombre "Ensalada caprese") (tipo primero) (temporada verano) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes tomate mozzarella albahaca))
   (plato (nombre "Ensalada Waldorf") (tipo primero) (temporada otoño) (estilo clasico) (vegetariano si) (precio 7) (ingredientes manzana apio nueces mayonesa))
   (plato (nombre "Ensalada de pasta") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 6) (ingredientes pasta tomate aceitunas))
   (plato (nombre "Ensalada de espinacas") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes espinacas fresas nueces))
   (plato (nombre "Ensalada de patata") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 5) (ingredientes patata mayonesa huevo))
   (plato (nombre "Ensalada de garbanzos") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 6) (ingredientes garbanzos pimiento cebolla))
   (plato (nombre "Ensalada de salmón") (tipo primero) (temporada verano) (estilo sibarita) (vegetariano no) (precio 9) (ingredientes salmón aguacate rucula))
   (plato (nombre "Ensalada de frutas") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 6) (ingredientes mango papaya kiwi))
   (plato (nombre "Ensalada de remolacha") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 6) (ingredientes remolacha queso-de-cabra nueces))
   (plato (nombre "Ensalada de aguacate") (tipo primero) (temporada verano) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes aguacate tomate cebolla))
   (plato (nombre "Ensalada de lentejas") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 6) (ingredientes lentejas pimiento cebolla))
   (plato (nombre "Ensalada de couscous") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 7) (ingredientes couscous menta limon))
   (plato (nombre "Ensalada de col") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano si) (precio 5) (ingredientes col zanahoria mayonesa))
   (plato (nombre "Ensalada de endivias") (tipo primero) (temporada invierno) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes endivias nueces queso))
   (plato (nombre "Ensalada de atún") (tipo primero) (temporada verano) (estilo clasico) (vegetariano no) (precio 7) (ingredientes atún tomate huevo))
   (plato (nombre "Ensalada de jamón") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 8) (ingredientes jamón melon queso))
   (plato (nombre "Ensalada de berenjena") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 6) (ingredientes berenjena tomate albahaca))
   (plato (nombre "Ensalada de pepino") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 5) (ingredientes pepino yogur menta))
   (plato (nombre "Ensalada de manzana") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 6) (ingredientes manzana apio nueces))
   (plato (nombre "Ensalada de arroz") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 6) (ingredientes arroz pimiento maiz))
   (plato (nombre "Ensalada de pollo") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 8) (ingredientes pollo lechuga maiz))
   (plato (nombre "Ensalada de garbanzos") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 6) (ingredientes garbanzos pimiento cebolla))
   (plato (nombre "Ensalada de remolacha") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 6) (ingredientes remolacha queso-de-cabra nueces))
   (plato (nombre "Ensalada de aguacate") (tipo primero) (temporada verano) (estilo sibarita) (vegetariano si) (precio 8) (ingredientes aguacate tomate cebolla))
   (plato (nombre "Ensalada de lentejas") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 6) (ingredientes lentejas pimiento cebolla))
   (plato (nombre "Ensalada de couscous") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 7) (ingredientes couscous menta limon))
   (plato (nombre "Ensalada de col") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano si) (precio 5) (ingredientes col zanahoria mayonesa))
   (plato (nombre "Ensalada de endivias") (tipo primero) (temporada invierno) (estilo sibarita) (vegetariano si) (precio 7) (ingredientes endivias nueces queso))
   (plato (nombre "Ensalada de atún") (tipo primero) (temporada verano) (estilo clasico) (vegetariano no) (precio 7) (ingredientes atún tomate huevo))
   (plato (nombre "Ensalada de jamón") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 8) (ingredientes jamón melon queso))
   (plato (nombre "Ensalada de berenjena") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 6) (ingredientes berenjena tomate albahaca))
   (plato (nombre "Ensalada de pepino") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 5) (ingredientes pepino yogur menta))
   (plato (nombre "Ensalada de manzana") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 6) (ingredientes manzana apio nueces))
   (plato (nombre "Ensalada de arroz") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 6) (ingredientes arroz pimiento maiz))
   (plato (nombre "Ensalada de pollo") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 8) (ingredientes pollo lechuga maiz))

   ;; Otros primeros platos (50)
   (plato (nombre "Carpaccio de ternera") (tipo primero) (temporada todo) (estilo sibarita) (vegetariano no) (precio 10) (ingredientes ternera rucula parmesano))
   (plato (nombre "Tartar de atún") (tipo primero) (temporada verano) (estilo sibarita) (vegetariano no) (precio 12) (ingredientes atun aguacate sésamo))
   (plato (nombre "Bruschetta") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 5) (ingredientes pan tomate albahaca))
   (plato (nombre "Hummus") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 5) (ingredientes garbanzos tahini limon))
   (plato (nombre "Tabule") (tipo primero) (temporada verano) (estilo regional) (vegetariano si) (precio 6) (ingredientes couscous perejil menta))
   (plato (nombre "Empanadillas") (tipo primero) (temporada todo) (estilo regional) (vegetariano no) (precio 6) (ingredientes carne masa cebolla))
   (plato (nombre "Croquetas de jamón") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes jamon bechamel pan))
   (plato (nombre "Patatas bravas") (tipo primero) (temporada todo) (estilo regional) (vegetariano si) (precio 5) (ingredientes patatas salsa-brava))
   (plato (nombre "Pimientos rellenos") (tipo primero) (temporada verano) (estilo regional) (vegetariano si) (precio 7) (ingredientes pimiento arroz tomate))
   (plato (nombre "Tosta de anchoas") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 6) (ingredientes pan anchoas mantequilla))
   (plato (nombre "Aguacates rellenos") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 8) (ingredientes aguacate gambas mayonesa))
   (plato (nombre "Ensaladilla rusa") (tipo primero) (temporada todo) (estilo clasico) (vegetariano si) (precio 6) (ingredientes patata zanahoria mayonesa))
   (plato (nombre "Revuelto de setas") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 7) (ingredientes huevo setas ajo))
   (plato (nombre "Tortilla de patatas") (tipo primero) (temporada todo) (estilo regional) (vegetariano si) (precio 6) (ingredientes patata huevo cebolla))
   (plato (nombre "Calamares a la romana") (tipo primero) (temporada todo) (estilo regional) (vegetariano no) (precio 8) (ingredientes calamar harina limon))
   (plato (nombre "Gambas al ajillo") (tipo primero) (temporada todo) (estilo regional) (vegetariano no) (precio 9) (ingredientes gambas ajo guindilla))
   (plato (nombre "Mejillones al vapor") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 8) (ingredientes mejillones limon perejil))
   (plato (nombre "Alcachofas a la plancha") (tipo primero) (temporada primavera) (estilo moderno) (vegetariano si) (precio 7) (ingredientes alcachofas ajo limon))
   (plato (nombre "Berenjenas a la parmesana") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 7) (ingredientes berenjena tomate queso))
   (plato (nombre "Canelones de espinacas") (tipo primero) (temporada invierno) (estilo clasico) (vegetariano si) (precio 8) (ingredientes espinacas queso bechamel))
   (plato (nombre "Lasaña vegetal") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 9) (ingredientes berenjena calabacin queso))
   (plato (nombre "Ratatouille") (tipo primero) (temporada verano) (estilo regional) (vegetariano si) (precio 7) (ingredientes berenjena calabacin tomate))
   (plato (nombre "Falafel") (tipo primero) (temporada todo) (estilo regional) (vegetariano si) (precio 6) (ingredientes garbanzos ajo comino))
   (plato (nombre "Samosa") (tipo primero) (temporada todo) (estilo regional) (vegetariano si) (precio 5) (ingredientes patata especias masa))
   (plato (nombre "Gyozas") (tipo primero) (temporada todo) (estilo moderno) (vegetariano no) (precio 7) (ingredientes cerdo repollo jengibre))
   (plato (nombre "Nachos con guacamole") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 6) (ingredientes nachos aguacate tomate))
   (plato (nombre "Queso a la plancha") (tipo primero) (temporada todo) (estilo clasico) (vegetariano si) (precio 7) (ingredientes queso mermelada nueces))
   (plato (nombre "Berenjenas con miel") (tipo primero) (temporada verano) (estilo regional) (vegetariano si) (precio 6) (ingredientes berenjena miel sésamo))
   (plato (nombre "Tosta de tomate") (tipo primero) (temporada verano) (estilo clasico) (vegetariano si) (precio 5) (ingredientes pan tomate aceite))
   (plato (nombre "Tosta de salmón") (tipo primero) (temporada todo) (estilo sibarita) (vegetariano no) (precio 9) (ingredientes pan salmón queso))
   (plato (nombre "Tosta de foie") (tipo primero) (temporada invierno) (estilo sibarita) (vegetariano no) (precio 12) (ingredientes pan foie mermelada))
   (plato (nombre "Tosta de champiñones") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan champiñones ajo))
   (plato (nombre "Tosta de queso de cabra") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan queso-de-cabra miel))
   (plato (nombre "Tosta de anchoas") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 6) (ingredientes pan anchoas mantequilla))
   (plato (nombre "Tosta de aguacate") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan aguacate huevo))
   (plato (nombre "Tosta de jamón") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes pan jamon tomate))
   (plato (nombre "Tosta de atún") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes pan atun mayonesa))
   (plato (nombre "Tosta de pollo") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes pan pollo lechuga))
   (plato (nombre "Tosta de verduras") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 6) (ingredientes pan berenjena calabacin))
   (plato (nombre "Tosta de setas") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan setas ajo))
   (plato (nombre "Tosta de salchichón") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 6) (ingredientes pan salchichon queso))
   (plato (nombre "Tosta de mortadela") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 6) (ingredientes pan mortadela queso))
   (plato (nombre "Tosta de chorizo") (tipo primero) (temporada todo) (estilo regional) (vegetariano no) (precio 6) (ingredientes pan chorizo queso))
   (plato (nombre "Tosta de lomo") (tipo primero) (temporada todo) (estilo regional) (vegetariano no) (precio 7) (ingredientes pan lomo queso))
   (plato (nombre "Tosta de bacon") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes pan bacon huevo))
   (plato (nombre "Tosta de salami") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 6) (ingredientes pan salami queso))
   (plato (nombre "Tosta de pavo") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 6) (ingredientes pan pavo queso))
   (plato (nombre "Tosta de ternera") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes pan ternera queso))
   (plato (nombre "Tosta de paté") (tipo primero) (temporada todo) (estilo clasico) (vegetariano no) (precio 6) (ingredientes pan paté pepinillo))
   (plato (nombre "Tosta de sardinas") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 7) (ingredientes pan sardinas pimiento))
   (plato (nombre "Tosta de boquerones") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 7) (ingredientes pan boquerones ajo))
   (plato (nombre "Tosta de ventresca") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 8) (ingredientes pan ventresca pimiento))
   (plato (nombre "Tosta de bonito") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 8) (ingredientes pan bonito tomate))
   (plato (nombre "Tosta de caballa") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 7) (ingredientes pan caballa pimiento))
   (plato (nombre "Tosta de melón con jamón") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 8) (ingredientes pan melon jamon))
   (plato (nombre "Tosta de higos con jamón") (tipo primero) (temporada verano) (estilo regional) (vegetariano no) (precio 8) (ingredientes pan higos jamon))
   (plato (nombre "Tosta de pera con queso") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan pera queso))
   (plato (nombre "Tosta de manzana con queso") (tipo primero) (temporada otoño) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan manzana queso))
   (plato (nombre "Tosta de membrillo con queso") (tipo primero) (temporada otoño) (estilo regional) (vegetariano si) (precio 7) (ingredientes pan membrillo queso))
   (plato (nombre "Tosta de nueces con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan nueces queso))
   (plato (nombre "Tosta de almendras con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan almendras queso))
   (plato (nombre "Tosta de pasas con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan pasas queso))
   (plato (nombre "Tosta de dátiles con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan datiles queso))
   (plato (nombre "Tosta de miel con queso") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan miel queso))
   (plato (nombre "Tosta de mermelada con queso") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan mermelada queso))
   (plato (nombre "Tosta de chocolate con queso") (tipo primero) (temporada todo) (estilo moderno) (vegetariano si) (precio 7) (ingredientes pan chocolate queso))
   (plato (nombre "Tosta de frutos secos con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutos-secos queso))
   (plato (nombre "Tosta de frutas con queso") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas queso))
   (plato (nombre "Tosta de frutos rojos con queso") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutos-rojos queso))
   (plato (nombre "Tosta de frutas tropicales con queso") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-tropicales queso))
   (plato (nombre "Tosta de frutas del bosque con queso") (tipo primero) (temporada verano) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-bosque queso))
   (plato (nombre "Tosta de frutas secas con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-secas queso))
   (plato (nombre "Tosta de frutas deshidratadas con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-deshidratadas queso))
   (plato (nombre "Tosta de frutas confitadas con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-confitadas queso))
   (plato (nombre "Tosta de frutas escarchadas con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-escarchadas queso))
   (plato (nombre "Tosta de frutas glaseadas con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-glaseadas queso))
   (plato (nombre "Tosta de frutas caramelizadas con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-caramelizadas queso))
   (plato (nombre "Tosta de frutas en almíbar con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-almibar queso))
   (plato (nombre "Tosta de frutas en conserva con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-conserva queso))
   (plato (nombre "Tosta de frutas en jarabe con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-jarabe queso))
   (plato (nombre "Tosta de frutas en compota con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-compota queso))
   (plato (nombre "Tosta de frutas en mermelada con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-mermelada queso))
   (plato (nombre "Tosta de frutas en puré con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-pure queso))
   (plato (nombre "Tosta de frutas en salsa con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-salsa queso))
   (plato (nombre "Tosta de frutas en crema con queso") (tipo primero) (temporada invierno) (estilo moderno) (vegetariano si) (precio 8) (ingredientes pan frutas-crema queso))
)