;; ========== SEGUNDOS PLATOS (100) ==========
(deffacts segundos-platos
   ;; ===== CARNES (30) =====
   (plato (nombre "Solomillo al vino") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 15) (ingredientes solomillo vino ajo))
   (plato (nombre "Carrillada ibérica") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 12) (ingredientes carrillera vino cebolla))
   (plato (nombre "Cordero asado") (tipo segundo) (temporada invierno) (estilo clasico) (vegetariano no) (precio 14) (ingredientes cordero romero patatas))
   (plato (nombre "Pollo al ajillo") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 10) (ingredientes pollo ajo perejil))
   (plato (nombre "Chuleta de cerdo") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 11) (ingredientes cerdo pimienta limon))
   (plato (nombre "Rabo de toro") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 13) (ingredientes rabo vino zanahoria))
   (plato (nombre "Costillas BBQ") (tipo segundo) (temporada verano) (estilo moderno) (vegetariano no) (precio 12) (ingredientes costillas salsa-bbq miel))
   (plato (nombre "Albóndigas en salsa") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 9) (ingredientes carne salsa tomate))
   (plato (nombre "Estofado de ternera") (tipo segundo) (temporada invierno) (estilo clasico) (vegetariano no) (precio 11) (ingredientes ternera patata cebolla))
   (plato (nombre "Entrecot a la parrilla") (tipo segundo) (temporada todo) (estilo sibarita) (vegetariano no) (precio 16) (ingredientes entrecot sal pimienta))
   (plato (nombre "Lomo de cerdo al horno") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 10) (ingredientes lomo ajo romero))
   (plato (nombre "Riñones al jerez") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 11) (ingredientes riñones jerez cebolla))
   (plato (nombre "Hígado encebollado") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 9) (ingredientes higado cebolla vinagre))
   (plato (nombre "Codillo asado") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 13) (ingredientes codillo cerveza patatas))
   (plato (nombre "Pato a la naranja") (tipo segundo) (temporada otoño) (estilo sibarita) (vegetariano no) (precio 18) (ingredientes pato naranja miel))
   (plato (nombre "Conejo al ajillo") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 12) (ingredientes conejo ajo vino))
   (plato (nombre "Chuletón de buey") (tipo segundo) (temporada todo) (estilo sibarita) (vegetariano no) (precio 20) (ingredientes chuleton sal pimienta))
   (plato (nombre "Morcilla de Burgos") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 8) (ingredientes morcilla cebolla pan))
   (plato (nombre "Callos a la madrileña") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 11) (ingredientes callos chorizo tomate))
   (plato (nombre "Presa ibérica") (tipo segundo) (temporada todo) (estilo sibarita) (vegetariano no) (precio 17) (ingredientes presa sal pimenton))
   (plato (nombre "Secreto ibérico") (tipo segundo) (temporada todo) (estilo sibarita) (vegetariano no) (precio 16) (ingredientes secreto ajo perejil))
   (plato (nombre "Pluma ibérica") (tipo segundo) (temporada todo) (estilo sibarita) (vegetariano no) (precio 15) (ingredientes pluma sal romero))
   (plato (nombre "Fricandó") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 12) (ingredientes ternera setas cebolla))
   (plato (nombre "Escudella") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 11) (ingredientes carne garbanzos patata))
   (plato (nombre "Lengua estofada") (tipo segundo) (temporada invierno) (estilo clasico) (vegetariano no) (precio 10) (ingredientes lengua vino cebolla))
   (plato (nombre "Mollejas a la plancha") (tipo segundo) (temporada todo) (estilo sibarita) (vegetariano no) (precio 14) (ingredientes mollejas limon sal))
   (plato (nombre "Cabrito al horno") (tipo segundo) (temporada primavera) (estilo regional) (vegetariano no) (precio 15) (ingredientes cabrito ajo romero))
   (plato (nombre "Chorizo a la sidra") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 8) (ingredientes chorizo sidra cebolla))
   (plato (nombre "Pinchos morunos") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 9) (ingredientes carne especias limon))
   (plato (nombre "Salchichas al vino") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 7) (ingredientes salchichas vino cebolla))

   ;; ===== PESCADOS Y MARISCOS (25) =====
   (plato (nombre "Bacalao al pil-pil") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 14) (ingredientes bacalao ajo aceite))
   (plato (nombre "Merluza a la vasca") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 13) (ingredientes merluza almejas perejil))
   (plato (nombre "Dorada a la sal") (tipo segundo) (temporada verano) (estilo clasico) (vegetariano no) (precio 16) (ingredientes dorada sal limon))
   (plato (nombre "Lubina con patatas") (tipo segundo) (temporada verano) (estilo moderno) (vegetariano no) (precio 15) (ingredientes lubina patatas limon))
   (plato (nombre "Pulpo a la gallega") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 14) (ingredientes pulpo pimenton patata))
   (plato (nombre "Gambas al ajillo") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 12) (ingredientes gambas ajo guindilla))
   (plato (nombre "Calamares a la romana") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 11) (ingredientes calamares harina limon))
   (plato (nombre "Rodaballo al horno") (tipo segundo) (temporada verano) (estilo sibarita) (vegetariano no) (precio 18) (ingredientes rodaballo verduras limon))
   (plato (nombre "Salmón a la plancha") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 14) (ingredientes salmon limon eneldo))
   (plato (nombre "Atún rojo") (tipo segundo) (temporada verano) (estilo sibarita) (vegetariano no) (precio 20) (ingredientes atun sal pimienta))
   (plato (nombre "Rape al ajillo") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 16) (ingredientes rape ajo perejil))
   (plato (nombre "Mejillones al vapor") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 10) (ingredientes mejillones limon laurel))
   (plato (nombre "Almejas a la marinera") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 13) (ingredientes almejas ajo perejil))
   (plato (nombre "Cazón en adobo") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 11) (ingredientes cazon adobo limon))
   (plato (nombre "Boquerones en vinagre") (tipo segundo) (temporada verano) (estilo clasico) (vegetariano no) (precio 9) (ingredientes boquerones vinagre ajo))
   (plato (nombre "Sardinas asadas") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 10) (ingredientes sardinas sal limon))
   (plato (nombre "Chipirones en su tinta") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 15) (ingredientes chipirones tinta cebolla))
   (plato (nombre "Langostinos a la plancha") (tipo segundo) (temporada verano) (estilo sibarita) (vegetariano no) (precio 16) (ingredientes langostinos sal limon))
   (plato (nombre "Vieiras al horno") (tipo segundo) (temporada invierno) (estilo sibarita) (vegetariano no) (precio 18) (ingredientes vieiras pan ajo))
   (plato (nombre "Zamburiñas al ajillo") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 15) (ingredientes zamburiñas ajo perejil))
   (plato (nombre "Berberechos al vapor") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 12) (ingredientes berberechos limon laurel))
   (plato (nombre "Navajas a la plancha") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 14) (ingredientes navajas ajo perejil))
   (plato (nombre "Ostras naturales") (tipo segundo) (temporada invierno) (estilo sibarita) (vegetariano no) (precio 22) (ingredientes ostras limon pimienta))
   (plato (nombre "Bogavante a la parrilla") (tipo segundo) (temporada verano) (estilo sibarita) (vegetariano no) (precio 25) (ingredientes bogavante mantequilla limon))
   (plato (nombre "Centollo al horno") (tipo segundo) (temporada invierno) (estilo sibarita) (vegetariano no) (precio 24) (ingredientes centollo ajo perejil))

   ;; ===== VEGETARIANOS (20) =====
   (plato (nombre "Tofu salteado") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 9) (ingredientes tofu pimiento cebolla))
   (plato (nombre "Lasagna vegetal") (tipo segundo) (temporada invierno) (estilo moderno) (vegetariano si) (precio 11) (ingredientes berenjena calabacin queso))
   (plato (nombre "Hamburguesa de lentejas") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 10) (ingredientes lentejas avena especias))
   (plato (nombre "Curry de garbanzos") (tipo segundo) (temporada invierno) (estilo moderno) (vegetariano si) (precio 9) (ingredientes garbanzos leche-coco curry))
   (plato (nombre "Quiche de espinacas") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 10) (ingredientes espinacas huevo queso))
   (plato (nombre "Milanesa de berenjena") (tipo segundo) (temporada verano) (estilo moderno) (vegetariano si) (precio 9) (ingredientes berenjena pan rallado queso))
   (plato (nombre "Falafel") (tipo segundo) (temporada todo) (estilo regional) (vegetariano si) (precio 8) (ingredientes garbanzos ajo comino))
   (plato (nombre "Ratatouille") (tipo segundo) (temporada verano) (estilo regional) (vegetariano si) (precio 10) (ingredientes berenjena calabacin tomate))
   (plato (nombre "Espaguetis a la puttanesca") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 9) (ingredientes pasta tomate alcaparras))
   (plato (nombre "Risotto de champiñones") (tipo segundo) (temporada otoño) (estilo sibarita) (vegetariano si) (precio 12) (ingredientes arroz setas parmesano))
   (plato (nombre "Tarta de verduras") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 10) (ingredientes calabacin zanahoria huevo))
   (plato (nombre "Empanadillas de queso") (tipo segundo) (temporada todo) (estilo regional) (vegetariano si) (precio 8) (ingredientes queso masa cebolla))
   (plato (nombre "Pisto con huevo") (tipo segundo) (temporada verano) (estilo regional) (vegetariano si) (precio 9) (ingredientes calabacin tomate huevo))
   (plato (nombre "Canelones de espinacas") (tipo segundo) (temporada invierno) (estilo clasico) (vegetariano si) (precio 11) (ingredientes espinacas bechamel queso))
   (plato (nombre "Albóndigas de quinoa") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 10) (ingredientes quinoa lentejas especias))
   (plato (nombre "Berenjenas rellenas") (tipo segundo) (temporada verano) (estilo moderno) (vegetariano si) (precio 10) (ingredientes berenjena arroz tomate))
   (plato (nombre "Tortilla de patata vegana") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 8) (ingredientes garbanzos cebolla patata))
   (plato (nombre "Wok de verduras") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 9) (ingredientes pimiento zanahoria brocoli))
   (plato (nombre "Gratinado de coliflor") (tipo segundo) (temporada invierno) (estilo moderno) (vegetariano si) (precio 10) (ingredientes coliflor bechamel queso))
   (plato (nombre "Fajitas vegetales") (tipo segundo) (temporada verano) (estilo moderno) (vegetariano si) (precio 9) (ingredientes pimiento cebolla tortilla))

   ;; ===== INTERNACIONALES (25) =====
   (plato (nombre "Paella valenciana") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 14) (ingredientes arroz pollo conejo))
   (plato (nombre "Pasta carbonara") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 11) (ingredientes pasta huevo bacon))
   (plato (nombre "Moussaka griega") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 12) (ingredientes berenjena carne bechamel))
   (plato (nombre "Tacos al pastor") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 10) (ingredientes cerdo piña tortilla))
   (plato (nombre "Pizza margarita") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano si) (precio 9) (ingredientes masa tomate mozzarella))
   (plato (nombre "Pad thai") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano no) (precio 11) (ingredientes fideos pollo cacahuete))
   (plato (nombre "Sushi variado") (tipo segundo) (temporada todo) (estilo sibarita) (vegetariano no) (precio 16) (ingredientes arroz salmon aguacate))
   (plato (nombre "Feijoada brasileña") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 13) (ingredientes cerdo judias arroz))
   (plato (nombre "Couscous marroquí") (tipo segundo) (temporada todo) (estilo regional) (vegetariano si) (precio 10) (ingredientes couscous verduras garbanzos))
   (plato (nombre "Goulash húngaro") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 12) (ingredientes ternera pimenton cebolla))
   (plato (nombre "Dumplings chinos") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano no) (precio 10) (ingredientes masa cerdo jengibre))
   (plato (nombre "Ramen de cerdo") (tipo segundo) (temporada invierno) (estilo moderno) (vegetariano no) (precio 12) (ingredientes fideos cerdo huevo))
   (plato (nombre "Boeuf bourguignon") (tipo segundo) (temporada invierno) (estilo sibarita) (vegetariano no) (precio 16) (ingredientes ternera vino cebolla))
   (plato (nombre "Fish and chips") (tipo segundo) (temporada todo) (estilo clasico) (vegetariano no) (precio 11) (ingredientes merluza patatas limon))
   (plato (nombre "Pollo tikka masala") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano no) (precio 12) (ingredientes pollo curry leche-coco))
   (plato (nombre "Ceviche peruano") (tipo segundo) (temporada verano) (estilo regional) (vegetariano no) (precio 13) (ingredientes pescado limon cilantro))
   (plato (nombre "Fajitas de pollo") (tipo segundo) (temporada verano) (estilo moderno) (vegetariano no) (precio 11) (ingredientes pollo pimiento tortilla))
   (plato (nombre "Bibimbap coreano") (tipo segundo) (temporada todo) (estilo moderno) (vegetariano si) (precio 12) (ingredientes arroz verduras huevo))
   (plato (nombre "Poutine canadiense") (tipo segundo) (temporada invierno) (estilo moderno) (vegetariano no) (precio 10) (ingredientes patatas queso salsa))
   (plato (nombre "Jambalaya") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 13) (ingredientes arroz pollo chorizo))
   (plato (nombre "Tagine de cordero") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano no) (precio 14) (ingredientes cordero ciruelas especias))
   (plato (nombre "Arepa venezolana") (tipo segundo) (temporada todo) (estilo regional) (vegetariano si) (precio 8) (ingredientes maiz queso aguacate))
   (plato (nombre "Kebab turco") (tipo segundo) (temporada todo) (estilo regional) (vegetariano no) (precio 9) (ingredientes cordero pan ensalada))
   (plato (nombre "Borscht ruso") (tipo segundo) (temporada invierno) (estilo regional) (vegetariano si) (precio 10) (ingredientes remolacha col nata))
   (plato (nombre "Pho vietnamita") (tipo segundo) (temporada invierno) (estilo moderno) (vegetariano no) (precio 11) (ingredientes fideos ternera menta))
)